name: vector_db
description: A dart based on-device vector database.
version: 1.0.0

environment:
  sdk: ^3.2.4

# Add regular dependencies here.
dependencies:
  uuid: ^4.3.3
  path: ^1.8.0
  http: ^0.13.3
  ml_linalg: ^13.12.2
  path_provider: ^2.1.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
